### ISSUE TITLE
[Bug]: Unable to set/remove requirement text field values

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I expected to be able to add and remove values to the **Majors** text field but I'm unable to:
<img width="324" alt="Screen Shot 2023-01-25 at 4 03 38 PM" src="https://user-images.githubusercontent.com/8023233/214721552-ac956023-10e7-4353-8b54-e57df4e2ef03.png">

### Steps To Reproduce

1. Go to https://dreamscholars.org/scholarships/TA1xQwttiORhCvuiDesJ/edit
2. Try adding or removing majors, schools, or states in the **Eligibility Requirements** section.
3. It doesn't work :/

Per the console, the error is:

```
react-dom.production.min.js:101 Uncaught TypeError: a.setFieldValues is not a function
    at j (FormikAutocomplete.tsx:38:36)
    at ut (useAutocomplete.js:531:7)
    at pt (useAutocomplete.js:565:5)
    at xt (useAutocomplete.js:871:5)
```

### What devices are you experiencing the problem on?

Desktop

### What browsers are you seeing the problem in?

Chrome

**Comment by josueetcom** [comment]
Since we haven't worked on the project recently my guess is that one of the library package updates (probably a Formik or MUI one) renamed the `setFieldValues` function and this reached production undetected due to missing FormikAutocomplete test cases that actually interact with the UI element and add/remove values.
